### ISSUE TITLE
Why g''(c) not g''(x*) in the Taylor expansion, Analysis of Fixed Point Iteration

### ISSUE THREAD

**Issue by yeejoh** [mandli/intro-numerical-methods#1]
In 5_root_finding_optimization.ipynb, Analysis of Fixed Point Iteration part, it writes:

Using a Taylor expansion we know

$$g(x^* + e_k) = g(x^*) + g'(x^*) e_k + \frac{g''(c) e_k^2}{2}$$

$$x^* + e_{k+1} = g(x^*) + g'(x^*) e_k + \frac{g''(c) e_k^2}{2}$$

Why it's $$\frac{g''(c) e_k^2}{2}$$, instead of $$\frac{g''(x^*) e_k^2}{2}$$? Where does the $$c$$ come from?

**Comment by mandli** [comment]
You are right that strictly speaking the term there should have $x^*$ rather than $c$.  Here the $c$ is meant to represent a value between $x^*$ and $e_k$ which can minimize the error bound but is not critical.

That being said, I think your suggestion is more clear in the derivation so the change is worth making.  Thanks for the feedback!  I will make a PR and make sure you agree with the change.
